apiVersion: v1
kind: Service
metadata:
  name: alerting-ks-client-server
  namespace: kubesphere-monitoring-system
spec:
  selector:
    app: alerting-ks-client
  ports:
  - name:  http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alerting-ks-client
  name: alerting-ks-client
  namespace: kubesphere-monitoring-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerting-ks-client
  template:
    metadata:
      labels:
        app: alerting-ks-client
    spec:
      containers:
      - command:
        - /alerting/alerting-ks-client
        - -database=alert-client
        - -mysql=alerting-db.kubesphere-monitoring-system.svc
        - -mysql_port=3306
        - -user=root
        - -password=password
        - -dispatcher_service=alerting-dispatcher-server.kubesphere-monitoring-system.svc
        - -dispatcher_port=50000
        image: carmanzhang/alerting-ks-client:latest
        imagePullPolicy: Always
        name: alerting-ks-client
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 200Mi